# Generated by Django 6.0.5 on 2026-05-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
