# Generated by Django 6.0.5 on 2026-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_room_room_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(default='Khanna', max_length=100),
            preserve_default=False,
        ),
    ]
