# Generated by Django 6.0.2 on 2026-03-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
