# Generated by Django 6.0.2 on 2026-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_room_is_available'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('pg_property', 'room_number'), name='unique_room_per_pg'),
        ),
    ]
