# Generated by Django 6.0.2 on 2026-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_room_unique_room_per_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_balcony_room',
            field=models.BooleanField(default=False),
        ),
    ]
