# Generated by Django 6.0.5 on 2026-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgproperty',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='country',
            field=models.TextField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='postal_code',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='state',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
