# Generated by Django 6.0.5 on 2026-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_pgproperty_address_line_1_pgproperty_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgproperty',
            name='address',
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='address_line_1',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='city',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='country',
            field=models.TextField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='postal_code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='state',
            field=models.TextField(max_length=100),
        ),
    ]
