# Generated by Django 6.0.5 on 2026-06-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_pgproperty_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone_country_code',
            field=models.CharField(default='+91', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='country',
            field=models.TextField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='postal_code',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='state',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
