# Generated by Django 6.0.5 on 2026-07-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due', to='management.tenant'),
        ),
    ]
