# Generated by Django 6.0.5 on 2026-09-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_dues_refunded_amount_alter_dues_due_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='due',
        ),
        migrations.CreateModel(
            name='RefundAllocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_allocations', to='management.dues')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='management.refund')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refund', 'due'), name='unique_refund_due_allocation')],
            },
        ),
    ]
